### ISSUE TITLE
请教两个处注释中提及的问题

### ISSUE THREAD

**Issue by LongTengDao** [masx200/http-https-http2-polyglot#3]
https://github.com/masx200/http-https-http2-polyglot/blob/d29f4df1122d76f56d5a3fab27af45f1b88c052d/lib/index.ts#L59

我查看了node相关的文档或代码，没有发现不监听socket error会引发程序崩溃部分。这个是怎么测试出来的？

https://github.com/masx200/http-https-http2-polyglot/blob/d29f4df1122d76f56d5a3fab27af45f1b88c052d/lib/index.ts#L131

这里的意思是如果不用`on readable + read`而是`on data`会丢失？这是什么情况下会发生的？按理说这已经属于node的严重bug了吧

**Comment by masx200** [comment]
1.这个是测试出来的,如果socket发生错误,则会报错

https://nodejs.org/dist/latest-v17.x/docs/api/events.html#error-events

**Comment by masx200** [comment]
2.这个不是bug,可以认为是feature,滑稽.
因为用`data`事件的话,读取到的就不止一个字节了,
用`readable`事件和`read`函数可以只读取一个字节.

> Attaching a 'data' event listener to a stream that has not been explicitly paused will switch the stream into flowing mode. Data will then be passed as soon as it is available.

https://nodejs.org/dist/latest-v17.x/docs/api/stream.html#event-data

https://nodejs.org/dist/latest-v17.x/docs/api/stream.html#event-readable

**Comment by LongTengDao** [comment]
非常感谢！
